apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLV8mYT1hIyotX19yamEtanokdnJrMTh6MjJoZUBhaiZlayQ9c2dydGExaTF0eGx0bF83
  DATABASE_PASSWORD: cG9zdGdyZXM=
  DATABASE_USERNAME: postgres
  DATABASE_NAME: postgress
